sudo: required

language: python

services:
  - docker
  
before_install:
  - docker build -t frankie567/twitterautoreplybot .
  - docker-compose up
  
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

# command to run tests
script: docker-compose run django python manage.py test
