version: '2'
services:
    db:
        image: postgres
    django:
        build: .
        working_dir: /code/twitterautoreplybot
        command: /usr/local/bin/gunicorn twitterautoreplybot.wsgi:application -w 2 -b :8000
        volumes:
            - .:/code
        expose:
            - "8000"
        depends_on:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - /www/static
        volumes_from:
            - django
        links:
            - django
